In [1]:
import pandas as po

#load the data set 
table = po.read_csv("students.csv")

#display first five rows
print(table.head())

  student_id   name   age          major   GPA
0       S001  Alice  20.0            ICT  3.40
1       S002    Bob  21.0   Data Science  3.70
2       S003  Carol  20.0            ICT  3.20
3       S004  David  22.0   Data Science  3.80
4       S005   Emma  21.0  Cybersecurity  3.55

In [2]:
#find number of rows and columns
print(table.shape)
print(f"Number of rows: {table.shape[0]}")
print(f"Number of columns: {table.shape[1]}")

(30, 5)
Number of rows: 30
Number of columns: 5

In [3]:
# Select name and GPA
print(table[["name", "GPA"]])

      name   GPA
0    Alice  3.40
1      Bob  3.70
2    Carol  3.20
3    David  3.80
4     Emma  3.55
5    Frank  3.10
6    Grace  3.85
7    Henry  2.95
8      Ivy  3.60
9     Jack  3.35
10    Kate  3.90
11     Leo   NaN
12     Mia  3.45
13    Noah  3.75
14  Olivia  3.50
15   Peter  3.15
16   Quinn  3.65
17    Rose  3.05
18     Sam  3.30
19    Tina  3.95
20     Uma  3.25
21  Victor  3.55
22   Wendy  3.70
23  Xavier  3.40
24    Yara   NaN
25    Zack  3.80
26    Anna  3.60
27   Brian  2.85
28   Chloe  3.90
29  Daniel  3.45

In [5]:
# Find students with GPA >= 3.5
print(table[table["GPA"] >= 3.5][["name", "GPA"]])

      name   GPA
1      Bob  3.70
3    David  3.80
4     Emma  3.55
6    Grace  3.85
8      Ivy  3.60
10    Kate  3.90
13    Noah  3.75
14  Olivia  3.50
16   Quinn  3.65
19    Tina  3.95
21  Victor  3.55
22   Wendy  3.70
25    Zack  3.80
26    Anna  3.60
28   Chloe  3.90

In [ ]:
#Sort students by GPA
table.sort_values("GPA")

   student_id    name   age                major   GPA
27       S028   Brian  22.0         Data Science  2.85
7        S008   Henry  22.0        Cybersecurity  2.95
17       S018    Rose  22.0  Applied Mathematics  3.05
5        S006   Frank  20.0  Applied Mathematics  3.10
15       S016   Peter  21.0         Data Science  3.15
2        S003   Carol  20.0                  ICT  3.20
20       S021     Uma  22.0        Cybersecurity  3.25
18       S019     Sam  21.0                  ICT  3.30
9        S010    Jack  21.0  Applied Mathematics  3.35
0        S001   Alice  20.0                  ICT  3.40
23       S024  Xavier  22.0         Data Science  3.40
29       S030  Daniel  21.0  Applied Mathematics  3.45
12       S013     Mia  21.0        Cybersecurity  3.45
14       S015  Olivia   NaN                  ICT  3.50
4        S005    Emma  21.0        Cybersecurity  3.55
21       S022  Victor  21.0  Applied Mathematics  3.55
8        S009     Ivy  20.0         Data Science  3.60
26       S027    Anna  21.0                  ICT  3.60
16       S017   Quinn  20.0        Cybersecurity  3.65
22       S023   Wendy  20.0                  ICT  3.70
1        S002     Bob  21.0         Data Science  3.70
13       S014    Noah  22.0  Applied Mathematics  3.75
3        S004   David  22.0         Data Science  3.80
25       S026    Zack  20.0  Applied Mathematics  3.80
6        S007   Grace  21.0                  ICT  3.85
10       S011    Kate  22.0                  ICT  3.90
28       S029   Chloe  20.0        Cybersecurity  3.90
19       S020    Tina  20.0         Data Science  3.95
11       S012     Leo  20.0         Data Science   NaN
24       S025    Yara  21.0        Cybersecurity   NaN

In [ ]:
# Find average GPA by major
print(table.groupby("major")["GPA"].mean())

major
Applied Mathematics    3.435714
Cybersecurity          3.458333
Data Science           3.492857
ICT                    3.556250
Name: GPA, dtype: float64

In [11]:
#Load both files
table = po.read_csv("students.csv")
df = po.read_csv("scores.csv")
print(table)
print(df)

   student_id    name   age                major   GPA
0        S001   Alice  20.0                  ICT  3.40
1        S002     Bob  21.0         Data Science  3.70
2        S003   Carol  20.0                  ICT  3.20
3        S004   David  22.0         Data Science  3.80
4        S005    Emma  21.0        Cybersecurity  3.55
5        S006   Frank  20.0  Applied Mathematics  3.10
6        S007   Grace  21.0                  ICT  3.85
7        S008   Henry  22.0        Cybersecurity  2.95
8        S009     Ivy  20.0         Data Science  3.60
9        S010    Jack  21.0  Applied Mathematics  3.35
10       S011    Kate  22.0                  ICT  3.90
11       S012     Leo  20.0         Data Science   NaN
12       S013     Mia  21.0        Cybersecurity  3.45
13       S014    Noah  22.0  Applied Mathematics  3.75
14       S015  Olivia   NaN                  ICT  3.50
15       S016   Peter  21.0         Data Science  3.15
16       S017   Quinn  20.0        Cybersecurity  3.65
17       S018    Rose  22.0  Applied Mathematics  3.05
18       S019     Sam  21.0                  ICT  3.30
19       S020    Tina  20.0         Data Science  3.95
20       S021     Uma  22.0        Cybersecurity  3.25
21       S022  Victor  21.0  Applied Mathematics  3.55
22       S023   Wendy  20.0                  ICT  3.70
23       S024  Xavier  22.0         Data Science  3.40
24       S025    Yara  21.0        Cybersecurity   NaN
25       S026    Zack  20.0  Applied Mathematics  3.80
26       S027    Anna  21.0                  ICT  3.60
27       S028   Brian  22.0         Data Science  2.85
28       S029   Chloe  20.0        Cybersecurity  3.90
29       S030  Daniel  21.0  Applied Mathematics  3.45
   student_id  python  math  database
0        S001      85  80.0      88.0
1        S002      92  88.0      90.0
2        S003      78  82.0      76.0
3        S004      95  91.0      94.0
4        S005      89  84.0      91.0
5        S006      74  86.0      72.0
6        S007      96  90.0      93.0
7        S008      70  75.0      68.0
8        S009      91  89.0      87.0
9        S010      82  93.0      79.0
10       S011      97  92.0      96.0
11       S012      84   NaN      81.0
12       S013      88  83.0      90.0
13       S014      90  95.0      86.0
14       S015      86  79.0      85.0
15       S016      77  81.0      80.0
16       S017      93  85.0      92.0
17       S018      72  88.0      74.0
18       S019      80  78.0      82.0
19       S020      98  94.0      97.0
20       S021      79  76.0      84.0
21       S022      87  91.0      83.0
22       S023      94  86.0      89.0
23       S024      83  85.0       NaN
24       S025      81  80.0      86.0
25       S026      92  97.0      88.0
26       S027      89  87.0      91.0
27       S028      69  74.0      71.0
28       S029      96   NaN      95.0
29       S030      84  90.0      82.0

In [ ]:
# Check missing values
print(table.isnull().sum())
print(df.isnull().sum())

student_id    0
name          0
age           1
major         0
GPA           2
dtype: int64
student_id    0
python        0
math          2
database      1
dtype: int64

In [ ]:
# Fill missing data in students.csv
table["age"] = table["age"].fillna(table["age"].mean()) 
table["GPA"] = table["GPA"].fillna(table["GPA"].mean())
print(table)

   student_id    name        age                major       GPA
0        S001   Alice  20.000000                  ICT  3.400000
1        S002     Bob  21.000000         Data Science  3.700000
2        S003   Carol  20.000000                  ICT  3.200000
3        S004   David  22.000000         Data Science  3.800000
4        S005    Emma  21.000000        Cybersecurity  3.550000
5        S006   Frank  20.000000  Applied Mathematics  3.100000
6        S007   Grace  21.000000                  ICT  3.850000
7        S008   Henry  22.000000        Cybersecurity  2.950000
8        S009     Ivy  20.000000         Data Science  3.600000
9        S010    Jack  21.000000  Applied Mathematics  3.350000
10       S011    Kate  22.000000                  ICT  3.900000
11       S012     Leo  20.000000         Data Science  3.489286
12       S013     Mia  21.000000        Cybersecurity  3.450000
13       S014    Noah  22.000000  Applied Mathematics  3.750000
14       S015  Olivia  20.931034                  ICT  3.500000
15       S016   Peter  21.000000         Data Science  3.150000
16       S017   Quinn  20.000000        Cybersecurity  3.650000
17       S018    Rose  22.000000  Applied Mathematics  3.050000
18       S019     Sam  21.000000                  ICT  3.300000
19       S020    Tina  20.000000         Data Science  3.950000
20       S021     Uma  22.000000        Cybersecurity  3.250000
21       S022  Victor  21.000000  Applied Mathematics  3.550000
22       S023   Wendy  20.000000                  ICT  3.700000
23       S024  Xavier  22.000000         Data Science  3.400000
24       S025    Yara  21.000000        Cybersecurity  3.489286
25       S026    Zack  20.000000  Applied Mathematics  3.800000
26       S027    Anna  21.000000                  ICT  3.600000
27       S028   Brian  22.000000         Data Science  2.850000
28       S029   Chloe  20.000000        Cybersecurity  3.900000
29       S030  Daniel  21.000000  Applied Mathematics  3.450000

In [13]:
# Fill missing data in scores.csv
df["math"] = df["math"].fillna(df["math"].mean())
df["database"] = df["database"].fillna(df["database"].mean())
print(df)

   student_id  python       math   database
0        S001      85  80.000000  88.000000
1        S002      92  88.000000  90.000000
2        S003      78  82.000000  76.000000
3        S004      95  91.000000  94.000000
4        S005      89  84.000000  91.000000
5        S006      74  86.000000  72.000000
6        S007      96  90.000000  93.000000
7        S008      70  75.000000  68.000000
8        S009      91  89.000000  87.000000
9        S010      82  93.000000  79.000000
10       S011      97  92.000000  96.000000
11       S012      84  85.678571  81.000000
12       S013      88  83.000000  90.000000
13       S014      90  95.000000  86.000000
14       S015      86  79.000000  85.000000
15       S016      77  81.000000  80.000000
16       S017      93  85.000000  92.000000
17       S018      72  88.000000  74.000000
18       S019      80  78.000000  82.000000
19       S020      98  94.000000  97.000000
20       S021      79  76.000000  84.000000
21       S022      87  91.000000  83.000000
22       S023      94  86.000000  89.000000
23       S024      83  85.000000  85.172414
24       S025      81  80.000000  86.000000
25       S026      92  97.000000  88.000000
26       S027      89  87.000000  91.000000
27       S028      69  74.000000  71.000000
28       S029      96  85.678571  95.000000
29       S030      84  90.000000  82.000000

In [15]:
print(table.isnull().sum())
print(df.isnull().sum())

student_id    0
name          0
age           0
major         0
GPA           0
dtype: int64
student_id    0
python        0
math          0
database      0
dtype: int64

In [17]:
#Merge the two datasets 
import pandas as pd
merged = pd.merge(table, df, on="student_id")
merged

,student_id,name,age,major,GPA,python,math,database
0,S001,Alice,20.000000,ICT,3.400000,85,80.000000,88.000000
1,S002,Bob,21.000000,Data Science,3.700000,92,88.000000,90.000000
2,S003,Carol,20.000000,ICT,3.200000,78,82.000000,76.000000
3,S004,David,22.000000,Data Science,3.800000,95,91.000000,94.000000
4,S005,Emma,21.000000,Cybersecurity,3.550000,89,84.000000,91.000000
5,S006,Frank,20.000000,Applied Mathematics,3.100000,74,86.000000,72.000000
6,S007,Grace,21.000000,ICT,3.850000,96,90.000000,93.000000
7,S008,Henry,22.000000,Cybersecurity,2.950000,70,75.000000,68.000000
8,S009,Ivy,20.000000,Data Science,3.600000,91,89.000000,87.000000
9,S010,Jack,21.000000,Applied Mathematics,3.350000,82,93.000000,79.000000
10,S011,Kate,22.000000,ICT,3.900000,97,92.000000,96.000000
11,S012,Leo,20.000000,Data Science,3.489286,84,85.678571,81.000000
12,S013,Mia,21.000000,Cybersecurity,3.450000,88,83.000000,90.000000
13,S014,Noah,22.000000,Applied Mathematics,3.750000,90,95.000000,86.000000
14,S015,Olivia,20.931034,ICT,3.500000,86,79.000000,85.000000
15,S016,Peter,21.000000,Data Science,3.150000,77,81.000000,80.000000
16,S017,Quinn,20.000000,Cybersecurity,3.650000,93,85.000000,92.000000
17,S018,Rose,22.000000,Applied Mathematics,3.050000,72,88.000000,74.000000
18,S019,Sam,21.000000,ICT,3.300000,80,78.000000,82.000000
19,S020,Tina,20.000000,Data Science,3.950000,98,94.000000,97.000000
20,S021,Uma,22.000000,Cybersecurity,3.250000,79,76.000000,84.000000
21,S022,Victor,21.000000,Applied Mathematics,3.550000,87,91.000000,83.000000
22,S023,Wendy,20.000000,ICT,3.700000,94,86.000000,89.000000
23,S024,Xavier,22.000000,Data Science,3.400000,83,85.000000,85.172414
24,S025,Yara,21.000000,Cybersecurity,3.489286,81,80.000000,86.000000
25,S026,Zack,20.000000,Applied Mathematics,3.800000,92,97.000000,88.000000
26,S027,Anna,21.000000,ICT,3.600000,89,87.000000,91.000000
27,S028,Brian,22.000000,Data Science,2.850000,69,74.000000,71.000000
28,S029,Chloe,20.000000,Cybersecurity,3.900000,96,85.678571,95.000000
29,S030,Daniel,21.000000,Applied Mathematics,3.450000,84,90.000000,82.000000

In [18]:
# Calculate each student's average score
merged["average_score"] = merged[["python", "math", "database"]].mean(axis=1)

merged

,student_id,name,age,major,GPA,python,math,database,average_score
0,S001,Alice,20.000000,ICT,3.400000,85,80.000000,88.000000,84.333333
1,S002,Bob,21.000000,Data Science,3.700000,92,88.000000,90.000000,90.000000
2,S003,Carol,20.000000,ICT,3.200000,78,82.000000,76.000000,78.666667
3,S004,David,22.000000,Data Science,3.800000,95,91.000000,94.000000,93.333333
4,S005,Emma,21.000000,Cybersecurity,3.550000,89,84.000000,91.000000,88.000000
5,S006,Frank,20.000000,Applied Mathematics,3.100000,74,86.000000,72.000000,77.333333
6,S007,Grace,21.000000,ICT,3.850000,96,90.000000,93.000000,93.000000
7,S008,Henry,22.000000,Cybersecurity,2.950000,70,75.000000,68.000000,71.000000
8,S009,Ivy,20.000000,Data Science,3.600000,91,89.000000,87.000000,89.000000
9,S010,Jack,21.000000,Applied Mathematics,3.350000,82,93.000000,79.000000,84.666667
10,S011,Kate,22.000000,ICT,3.900000,97,92.000000,96.000000,95.000000
11,S012,Leo,20.000000,Data Science,3.489286,84,85.678571,81.000000,83.559524
12,S013,Mia,21.000000,Cybersecurity,3.450000,88,83.000000,90.000000,87.000000
13,S014,Noah,22.000000,Applied Mathematics,3.750000,90,95.000000,86.000000,90.333333
14,S015,Olivia,20.931034,ICT,3.500000,86,79.000000,85.000000,83.333333
15,S016,Peter,21.000000,Data Science,3.150000,77,81.000000,80.000000,79.333333
16,S017,Quinn,20.000000,Cybersecurity,3.650000,93,85.000000,92.000000,90.000000
17,S018,Rose,22.000000,Applied Mathematics,3.050000,72,88.000000,74.000000,78.000000
18,S019,Sam,21.000000,ICT,3.300000,80,78.000000,82.000000,80.000000
19,S020,Tina,20.000000,Data Science,3.950000,98,94.000000,97.000000,96.333333
20,S021,Uma,22.000000,Cybersecurity,3.250000,79,76.000000,84.000000,79.666667
21,S022,Victor,21.000000,Applied Mathematics,3.550000,87,91.000000,83.000000,87.000000
22,S023,Wendy,20.000000,ICT,3.700000,94,86.000000,89.000000,89.666667
23,S024,Xavier,22.000000,Data Science,3.400000,83,85.000000,85.172414,84.390805
24,S025,Yara,21.000000,Cybersecurity,3.489286,81,80.000000,86.000000,82.333333
25,S026,Zack,20.000000,Applied Mathematics,3.800000,92,97.000000,88.000000,92.333333
26,S027,Anna,21.000000,ICT,3.600000,89,87.000000,91.000000,89.000000
27,S028,Brian,22.000000,Data Science,2.850000,69,74.000000,71.000000,71.333333
28,S029,Chloe,20.000000,Cybersecurity,3.900000,96,85.678571,95.000000,92.226190
29,S030,Daniel,21.000000,Applied Mathematics,3.450000,84,90.000000,82.000000,85.333333

In [ ]:
# Find the top 5 students
merged.sort_values("average_score", ascending=False).head()

,student_id,name,age,major,GPA,python,math,database,average_score
19,S020,Tina,20.0,Data Science,3.95,98,94.0,97.0,96.333333
10,S011,Kate,22.0,ICT,3.90,97,92.0,96.0,95.000000
3,S004,David,22.0,Data Science,3.80,95,91.0,94.0,93.333333
6,S007,Grace,21.0,ICT,3.85,96,90.0,93.0,93.000000
25,S026,Zack,20.0,Applied Mathematics,3.80,92,97.0,88.0,92.333333

In [20]:
# Compute average score by major
merged.groupby("major")["average_score"].mean()

major
Applied Mathematics    85.000000
Cybersecurity          84.318027
Data Science           85.910458
ICT                    86.625000
Name: average_score, dtype: float64